// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyAssist.Infrastructure.Data.DataModel;

namespace StudyAssist.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StudyAssistContext))]
    [Migration("20181211095746_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudyAssist.Infrastructure.Data.DataModel.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StudyAssist.Infrastructure.Data.DataModel.Problem", b =>
                {
                    b.Property<int>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer");

                    b.Property<bool>("IsAutoRepeate");

                    b.Property<bool>("IsStudy");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("RepeatDate");

                    b.Property<int>("ThemeId");

                    b.HasKey("ProblemId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("StudyAssist.Infrastructure.Data.DataModel.Theme", b =>
                {
                    b.Property<int>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<bool>("IsStudy");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("ThemeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("StudyAssist.Infrastructure.Data.DataModel.Problem", b =>
                {
                    b.HasOne("StudyAssist.Infrastructure.Data.DataModel.Theme", "Theme")
                        .WithMany("Problems")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StudyAssist.Infrastructure.Data.DataModel.Theme", b =>
                {
                    b.HasOne("StudyAssist.Infrastructure.Data.DataModel.Category", "Category")
                        .WithMany("Themes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
